### ISSUE TITLE
Strict standard warning in Rb_EcommerceResponse set() fucntion

### ISSUE THREAD

**Issue by jainrimjhim20** [readybytes/rbframework#62]
Declaration of Rb_EcommerceResponse::set() should be compatible with Joomla\Registry\Registry::set($path, $value, $separator = NULL)

It is coming with joomla 3.4+

**Comment by rbslvivek** [comment]
Response - strict standard fixed
Request - pending (Comes in payment and transaction screen)
Strict standards: Declaration of Rb_EcommerceRequest::set() should be compatible with Joomla\Registry\Registry::set($path, $value, $separator = NULL) in /var/www/payinvoice4534/plugins/system/rbsl/rb/pkg/ecommerce/payment/request.php on line 48

**Comment by rbslvivek** [comment]
![selection_104](https://cloud.githubusercontent.com/assets/1694761/8926886/f2d57f84-3530-11e5-960e-1bb6e0813220.png)
![selection_103](https://cloud.githubusercontent.com/assets/1694761/8926887/f2d718d0-3530-11e5-9497-c96a8dce1ad9.png)
